#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Dec 22, 2015 07:53:47 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {DejaVu Sans} -size -12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 11 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra38
    set site_4_0 $site_3_0.scr43
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m39" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+458+135
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "RaschiettoManager"
    vTcl:DefineAlias "$top" "root" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 455 \
        -highlightcolor black -width 605 
    vTcl:DefineAlias "$top.fra38" "AppManager" vTcl:WidgetProc "root" 1
    set site_3_0 $top.fra38
    button $site_3_0.but40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#004000} -command runGulp -foreground white \
        -highlightcolor black -text {Esegui gulp!} 
    vTcl:DefineAlias "$site_3_0.but40" "GulpBtn" vTcl:WidgetProc "root" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr43 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr43" "Scrolledtext1" vTcl:WidgetProc "root" 1

    .top37.fra38.scr43.01 configure -background black \
        -borderwidth 2 \
        -exportselection 0 \
        -font font11 \
        -foreground lightgrey \
        -height 1 \
        -highlightbackground white \
        -highlightcolor black \
        -insertbackground white \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground white \
        -width 70 \
        -wrap none
    button $site_3_0.but37 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#af0000} -command runNpm \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground white \
        -highlightcolor black -text {Reinstalla librerie JS} 
    vTcl:DefineAlias "$site_3_0.but37" "Button1" vTcl:WidgetProc "root" 1
    button $site_3_0.but38 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#af0000} -command runPip \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground white -height 37 \
        -highlightcolor black -text {Reinstalla librerie python} 
    vTcl:DefineAlias "$site_3_0.but38" "Button2" vTcl:WidgetProc "root" 1
    button $site_3_0.but39 \
        -activebackground {#d9d9d9} -activeforeground black -background red \
        -command doSetup -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground white -highlightcolor black -text {Reinstalla tutto} 
    vTcl:DefineAlias "$site_3_0.but39" "Button3" vTcl:WidgetProc "root" 1
    button $site_3_0.but41 \
        -activebackground {#d9d9d9} -activeforeground white \
        -background {#006400} -command runWatch \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#F1F1F1} \
        -highlightcolor black -text {Esegui gulp watch!!!} 
    vTcl:DefineAlias "$site_3_0.but41" "Button4" vTcl:WidgetProc "root" 1
    button $site_3_0.but42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background darkblue -command genApacheConf \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#ffffff} \
        -highlightcolor black -text {Genera conf apache} 
    vTcl:DefineAlias "$site_3_0.but42" "Button5" vTcl:WidgetProc "root" 1
    place $site_3_0.but40 \
        -in $site_3_0 -x 210 -y 50 -width 170 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr43 \
        -in $site_3_0 -x 2 -y 200 -width 597 -height 245 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but37 \
        -in $site_3_0 -x 411 -y 20 -width 170 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but38 \
        -in $site_3_0 -x 411 -y 70 -width 170 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but39 \
        -in $site_3_0 -x 410 -y 120 -width 170 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but41 \
        -in $site_3_0 -x 210 -y 100 -width 167 -height 77 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but42 \
        -in $site_3_0 -x 20 -y 20 -width 170 -height 40 -anchor nw \
        -bordermode ignore 
    menu $top.m39 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra38 \
        -in $top -x 0 -y 0 -width 605 -height 455 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

